twig:
  form_themes:
    - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
    - "bootstrap_4_layout.html.twig"

fos_ck_editor:
  default_config: basic_config
  configs:
    basic_config:
      toolbar: full
      filebrowserBrowseRoute: file_manager
      filebrowserBrowseRouteParameters:
        conf: files
        module: ckeditor
      filebrowserImageBrowseRoute: file_manager
      filebrowserImageBrowseRouteParameters:
        conf: default
        module: ckeditor
